import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";
import { staffGuard } from "@/lib/guards";
import { logAudit } from "@/lib/audit";
import { parseLineItems } from "@/lib/invoice-line-items";
import type { StaffRole } from "@/types";

const EDIT_ROLES: StaffRole[] = [
  "super_admin",
  "managing_partner",
  "sales_manager",
  "sales_rep",
  "ops_manager",
  "workshop_lead",
  "accountant",
];

const VAT_RATE = 7.5;

// Editable only before payment -- once a receipt exists (Mark Paid, or the
// invoice is a receipt itself), the receipt was generated by copying this
// row's line_items/totals at that moment. Editing afterward would leave
// the invoice and its own receipt silently disagreeing with each other.
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const staff = await staffGuard();
  if (!staff) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }
  if (!EDIT_ROLES.includes(staff.role as StaffRole)) {
    return NextResponse.json({ error: "Not permitted to edit invoices." }, { status: 403 });
  }

  const { id } = await params;
  const service = createServiceClient();

  const { data: invoice } = await service.from("invoices").select("doc_type, voided_at").eq("id", id).maybeSingle();
  if (!invoice) {
    return NextResponse.json({ error: "Invoice not found." }, { status: 404 });
  }
  if (invoice.doc_type !== "invoice") {
    return NextResponse.json({ error: "Only an invoice can be edited, not a receipt." }, { status: 400 });
  }
  if (invoice.voided_at) {
    return NextResponse.json({ error: "This invoice has been voided." }, { status: 400 });
  }
  const { data: existingReceipt } = await service.from("invoices").select("id").eq("related_invoice_id", id).maybeSingle();
  if (existingReceipt) {
    return NextResponse.json({ error: "Can't edit an invoice that's already been paid." }, { status: 400 });
  }

  const body = await request.json().catch(() => null);
  if (!body) {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const customerId = typeof body?.customer_id === "string" ? body.customer_id : "";
  const vehicleId = typeof body?.vehicle_id === "string" && body.vehicle_id ? body.vehicle_id : null;
  const vatExempt = body?.vat_exempt !== false;
  const notes = typeof body?.notes === "string" && body.notes.trim() ? body.notes.trim() : null;
  const lineItems = parseLineItems(body?.line_items);

  if (!customerId) {
    return NextResponse.json({ error: "Select a customer." }, { status: 400 });
  }
  if (lineItems.length === 0) {
    return NextResponse.json({ error: "Add at least one valid line item." }, { status: 400 });
  }

  const subtotalKobo = lineItems.reduce((sum, item) => sum + item.amount_kobo, 0);
  const vatAmountKobo = vatExempt ? 0 : Math.round(subtotalKobo * (VAT_RATE / 100));
  const totalKobo = subtotalKobo + vatAmountKobo;

  const submittedTin = typeof body?.customer_tin === "string" && body.customer_tin.trim() ? body.customer_tin.trim() : null;
  const { data: customer } = await service.from("customers").select("tin").eq("id", customerId).maybeSingle();
  const customerTin = submittedTin ?? customer?.tin ?? null;
  if (submittedTin && !customer?.tin) {
    await service.from("customers").update({ tin: submittedTin }).eq("id", customerId);
  }

  const { data: updated, error } = await service
    .from("invoices")
    .update({
      vehicle_id: vehicleId,
      customer_id: customerId,
      line_items: lineItems,
      subtotal_kobo: subtotalKobo,
      vat_rate: VAT_RATE,
      vat_exempt: vatExempt,
      vat_amount_kobo: vatAmountKobo,
      total_kobo: totalKobo,
      notes,
      customer_tin: customerTin,
      invoice_type_code: customerTin ? "B2B" : "B2C",
    })
    .eq("id", id)
    .select("id, invoice_number")
    .single();

  if (error || !updated) {
    return NextResponse.json({ error: "Could not save changes." }, { status: 500 });
  }

  await logAudit({
    userId: staff.id,
    action: "update",
    tableName: "invoices",
    recordId: id,
    newValue: { customer_id: customerId, total_kobo: totalKobo },
  });

  return NextResponse.json({ id: updated.id, invoiceNumber: updated.invoice_number });
}
